Repository kubernetes-csi/external-snapshotter, pull requests merged in 2018-11, with the labels that each got.

#49 fix readme deploy snapshotter command
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 deploy: split out RBAC definitions
  README.md
  deploy/kubernetes/README.md
  deploy/kubernetes/rbac-external-provisioner.yaml
  deploy/kubernetes/rbac.yaml
  deploy/kubernetes/setup-csi-snapshotter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#51 [clean up]fix some comment typo
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
  pkg/controller/snapshot_create_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#58 Breaking change: Update snapshotter to use CSI spec 1.0
  Gopkg.lock
  Gopkg.toml
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  pkg/controller/csi_handler.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_ready_test.go
  vendor/github.com/container-storage-interface/spec/.gitignore
  vendor/github.com/container-storage-interface/spec/.travis.yml
  vendor/github.com/container-storage-interface/spec/CCLA.pdf
  vendor/github.com/container-storage-interface/spec/CONTRIBUTING.md
  vendor/github.com/container-storage-interface/spec/OWNERS
  vendor/github.com/container-storage-interface/spec/README.md
  vendor/github.com/container-storage-interface/spec/VERSION
  vendor/github.com/container-storage-interface/spec/csi.proto
  vendor/github.com/container-storage-interface/spec/lib/go/Makefile
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/spec.md
  vendor/github.com/kubernetes-csi/csi-test/.gitignore
  vendor/github.com/kubernetes-csi/csi-test/.travis.yml
  vendor/github.com/kubernetes-csi/csi-test/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-test/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-test/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-test/Makefile
  vendor/github.com/kubernetes-csi/csi-test/README.md
  vendor/github.com/kubernetes-csi/csi-test/cmd/csi-sanity/sanity_test.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.mock.go
  vendor/github.com/kubernetes-csi/csi-test/hack/_apitest/api_test.go
  vendor/github.com/kubernetes-csi/csi-test/hack/_embedded/embedded_test.go
  vendor/github.com/kubernetes-csi/csi-test/hack/e2e.sh
  vendor/github.com/kubernetes-csi/csi-test/mock/README.md
  vendor/github.com/kubernetes-csi/csi-test/mock/cache/SnapshotCache.go
  vendor/github.com/kubernetes-csi/csi-test/mock/main.go
  vendor/github.com/kubernetes-csi/csi-test/mock/service/controller.go
  vendor/github.com/kubernetes-csi/csi-test/mock/service/identity.go
  vendor/github.com/kubernetes-csi/csi-test/mock/service/node.go
  vendor/github.com/kubernetes-csi/csi-test/mock/service/service.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/README.md
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/cleanup.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/identity.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go
  vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/sanity.go
  vendor/github.com/kubernetes-csi/csi-test/test/co_test.go
  vendor/github.com/kubernetes-csi/csi-test/test/driver_test.go
  vendor/github.com/kubernetes-csi/csi-test/utils/safegoroutinetester.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#56 fix RABC rule
  deploy/kubernetes/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Call CreateSnapshot to check if snapshot is processed
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_create_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#65 Use existing content name
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#40 Add volumesnapshot content deletion policy
  pkg/apis/volumesnapshot/v1alpha1/types.go
  pkg/apis/volumesnapshot/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshot.go
  pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshotclass.go
  pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshotcontent.go
  pkg/controller/csi_handler.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_test.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_delete_test.go
  pkg/controller/snapshot_ready_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#71 Rename Ready to ReadyToUse
  pkg/apis/volumesnapshot/v1alpha1/types.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#39 Add Finalizer for VolumeSnapshot and VolumeSnapshotContent
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_test.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_delete_test.go
  pkg/controller/snapshot_ready_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#72 add pvcLister to snapshot controller
  cmd/csi-snapshotter/main.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
  pkg/controller/snapshot_create_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#73 Revert "add pvcLister to snapshot controller"
  cmd/csi-snapshotter/main.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
  pkg/controller/snapshot_create_test.go
Labels: approved, cncf-cla: yes, size/S

#69 add myself as approver for snapshotter
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#74 Cherry-picking commits from master to release-1.0 branch
  deploy/kubernetes/setup-csi-snapshotter.yaml
  pkg/apis/volumesnapshot/v1alpha1/types.go
  pkg/apis/volumesnapshot/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshot.go
  pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshotclass.go
  pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/volumesnapshotcontent.go
  pkg/controller/csi_handler.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
  pkg/controller/snapshot_controller_test.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_delete_test.go
  pkg/controller/snapshot_ready_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, size/XL

#76 Use logging util
  Gopkg.lock
  Gopkg.toml
  pkg/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/OWNERS
  vendor/github.com/kubernetes-csi/csi-lib-utils/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-lib-utils/code-of-conduct.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/.gitignore
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest/csitest.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#77 Cherry-pick #76 to release-1.0: Use logging util
  Gopkg.lock
  Gopkg.toml
  pkg/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/CONTRIBUTING.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.lock
  vendor/github.com/kubernetes-csi/csi-lib-utils/Gopkg.toml
  vendor/github.com/kubernetes-csi/csi-lib-utils/LICENSE
  vendor/github.com/kubernetes-csi/csi-lib-utils/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/OWNERS
  vendor/github.com/kubernetes-csi/csi-lib-utils/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/SECURITY_CONTACTS
  vendor/github.com/kubernetes-csi/csi-lib-utils/code-of-conduct.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/protosanitizer_test.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/.gitignore
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/Makefile
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/README.md
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csi.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest.proto
  vendor/github.com/kubernetes-csi/csi-lib-utils/protosanitizer/test/csitest/csitest.pb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
