Repository kubernetes-csi/external-snapshotter, pull requests merged in 2018-09, with the labels that each got.

#21 cleanup remove unused code
  cmd/csi-snapshotter/create_crd.go
Labels: approved, lgtm, size/S

#23 remove class store since we donot update it in controller
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
Labels: approved, lgtm, size/S

#24 Fix updating restore size issue
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  pkg/controller/csi_handler.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
Labels: approved, lgtm, size/M

#18 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/M

#25 Add event scheme
  cmd/csi-snapshotter/main.go
  pkg/controller/snapshot_controller_base.go
Labels: approved, lgtm, size/XS

#17 Add example yaml files for deployment and testing
  deploy/kubernetes/setup-csi-snapshotter.yaml
  examples/kubernetes/pvc.yaml
  examples/kubernetes/restore.yaml
  examples/kubernetes/snapshot.yaml
  examples/kubernetes/snapshotclass.yaml
  examples/kubernetes/storageclass.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#29 Update vendor files for k8s.io/apiextensions-apiserver
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  vendor/k8s.io/apiextensions-apiserver/OWNERS
  vendor/k8s.io/apiextensions-apiserver/hack/update-codegen.sh
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/install/roundtrip_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/cmd/server/options/options.go
  vendor/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing/testdata/localhost_127.0.0.1_localhost.crt
  vendor/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing/testdata/localhost_127.0.0.1_localhost.key
  vendor/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing/testserver.go
  vendor/k8s.io/apiextensions-apiserver/pkg/controller/establish/establishing_controller.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/registry.go
  vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/basic_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/finalization_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/fixtures/resources.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/helpers.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/subresources_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/table_test.go
  vendor/k8s.io/apiextensions-apiserver/test/integration/validation_test.go
Labels: approved, cncf-cla: yes, size/XXL

#27 Fix restore size type in snapshot content
  pkg/apis/volumesnapshot/v1alpha1/types.go
  pkg/apis/volumesnapshot/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_create_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#31 Add more contents to readme file
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#32 Handle the CSI driver in VolumeSnapshotContent does not match case
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
  pkg/controller/snapshot_delete_test.go
  pkg/controller/snapshot_ready_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#33 Update snapshot class in the content spec
  pkg/controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#34 Update version in the Makefile
  Makefile
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#35 Update images to v0.4.0
  deploy/kubernetes/setup-csi-snapshotter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
