Repository kubernetes-csi/external-snapshotter, pull requests merged in 2019-03, with the labels that each got.

#101 Use distroless as base image
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 Deprecate --snapshotter option
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#88 Migrate to k8s.io/klog from glog.
  cmd/csi-snapshotter/create_crd.go
  cmd/csi-snapshotter/main.go
  pkg/connection/connection.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#105 update vendor to k8s 1.14.0
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/third_party/forked/godep/license.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#98 Fix for pre-bound snapshot empty source error
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_ready_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
