Repository kubernetes-csi/external-snapshotter, pull requests merged in 2019-01, with the labels that each got.

#75 add pvcLister to snapshot controller
  cmd/csi-snapshotter/main.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_base.go
  pkg/controller/snapshot_create_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#82 Update exported function details with source code comments.
  pkg/apis/volumesnapshot/v1alpha1/types.go
  pkg/connection/connection.go
  pkg/controller/csi_handler.go
  pkg/controller/snapshot_controller.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#81 Correct error variables and fix other golint errors.
  pkg/connection/connection_test.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#84 Correct markdown linter errors.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#80 Update images to 1.0.1
  deploy/kubernetes/setup-csi-snapshotter.yaml
Labels: approved, cncf-cla: yes, size/XS

#87 Update images to 1.0.1
  deploy/kubernetes/setup-csi-snapshotter.yaml
Labels: approved, lgtm, size/XS
