Repository kubernetes-csi/external-snapshotter, pull requests merged in 2019-04, with the labels that each got.

#97 Refactor external snapshotter to use csi-lib-utils/rpc
  Gopkg.lock
  Gopkg.toml
  cmd/csi-snapshotter/main.go
  cmd/csi-snapshotter/main_test.go
  pkg/connection/connection.go
  pkg/connection/connection_test.go
  pkg/controller/csi_handler.go
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller_base.go
  pkg/snapshotter/snapshotter.go
  pkg/snapshotter/snapshotter_test.go
  vendor/github.com/json-iterator/go/any.go
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_skip_strict.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_marshaler.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_openbsd_arm.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/internal/cgo/cgo.go
  vendor/golang.org/x/tools/go/internal/cgo/cgo_pkgconfig.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_fallback.go
  vendor/golang.org/x/tools/go/packages/golist_fallback_testmain.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/mod.go
  vendor/golang.org/x/tools/third_party/moduleloader/LICENSE
  vendor/golang.org/x/tools/third_party/typescript/LICENSE
  vendor/golang.org/x/tools/third_party/webcomponents/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/version.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/kubernetes/staging/src/k8s.io/component-base/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib/LICENSE
  vendor/k8s.io/kubernetes/staging/src/k8s.io/node-api/LICENSE
  vendor/k8s.io/kubernetes/third_party/swagger-ui/LICENSE
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#109 Update dependencies to k8s 1.13.1 from the release-1.0 branch
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/Godeps/Godeps.json
  vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  vendor/k8s.io/apiextensions-apiserver/OWNERS
  vendor/k8s.io/apimachinery/Godeps/Godeps.json
  vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/client-go/.travis.yml
  vendor/k8s.io/client-go/CHANGELOG.md
  vendor/k8s.io/client-go/Godeps/Godeps.json
  vendor/k8s.io/client-go/README.md
  vendor/k8s.io/client-go/rest/config.go
  vendor/k8s.io/client-go/rest/config_test.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config_test.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/client-go/transport/token_source.go
  vendor/k8s.io/client-go/transport/token_source_test.go
Labels: approved, cncf-cla: yes, kind/api-change, sig/api-machinery, sig/architecture, size/XXL

#107 Add Leader Election Support
  Gopkg.lock
  Gopkg.toml
  README.md
  cmd/csi-snapshotter/main.go
  deploy/kubernetes/rbac-external-provisioner.yaml
  deploy/kubernetes/rbac.yaml
  deploy/kubernetes/setup-csi-snapshotter.yaml
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-test/.travis.yml
  vendor/github.com/kubernetes-csi/csi-test/driver/driver-controller.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver-node.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.go
  vendor/github.com/kubernetes-csi/csi-test/driver/driver.mock.go
  vendor/github.com/kubernetes-csi/csi-test/driver/mock.go
  vendor/github.com/kubernetes-csi/csi-test/release-tools/LICENSE
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_386.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/imports/mkstdlib.go
  vendor/golang.org/x/tools/imports/zstdlib.go
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#111 Prow testing
  .prow.sh
  release-tools/.prow.sh
  release-tools/README.md
  release-tools/build.make
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
  release-tools/util.sh
  release-tools/verify-shellcheck.sh
  release-tools/verify-subtree.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#113 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#93 add csi timeout flag
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#104 Use discovered storageclassName to look up the storage class
  pkg/controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#114 Add change log for v1.1
  CHANGELOG-1.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#118 Fix the default timeout in help msg
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#47 Add Delete Volume Finalizer
  deploy/kubernetes/rbac.yaml
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_finalizer_test.go
  pkg/controller/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L
