Repository kubernetes-csi/external-snapshotter, pull requests merged in 2019-10, with the labels that each got.

#171 Exit on CSI gRPC conn loss
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#172 Verify PV/PVC binding and driver
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_ready_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#173 Cherry-pick: Verify PV/PVC binding and driver
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_ready_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#175 Cherry-pick to 1.0: Verify PV/PVC binding and driver
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_ready_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#177 Add changelog for v1.0.2
  CHANGELOG-1.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#180 Cherry-pick to 0.4: Verify PV/PVC binding and driver
  Makefile
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_ready_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#183 Run only unit tests for now
  .prow.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/XS

#184 Add changelog for v0.4.2
  CHANGELOG-0.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S
