Repository kubernetes-csi/external-snapshotter, pull requests merged in 2019-12, with the labels that each got.

#205 Update README to reflect go module usage
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#207 Add tests for shouldDelete function
  pkg/sidecar-controller/snapshot_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#210 sidecar controller update, fix potential snapshot leaking
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, release-note-none, size/L

#206 Update README
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#211 Remove createSnapshotContentRetryCount and createSnapshotContentInterval
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller_base.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/S

#217 Add a warning msg in the upgrade process
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/XS

#218 Fix err shadow in updateSnapshotStatus and add retry delay
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#220 Update common controller tests after split controller
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_finalizer_test.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#201 Update snapshot controller
  pkg/common-controller/snapshot_controller.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#226 Small fixes to snapshot-controller YAML
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#228 Remove unnecessary csi-translation-lib dep
  go.mod
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
