Repository kubernetes-csi/external-snapshotter, pull requests merged in 2019-09, with the labels that each got.

#165 Add deletion secret as annotation to content
  pkg/controller/framework_test.go
  pkg/controller/snapshot_controller.go
  pkg/controller/snapshot_controller_test.go
  pkg/controller/snapshot_create_test.go
  pkg/controller/snapshot_delete_test.go
  pkg/controller/snapshot_ready_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#169 Update csi-release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#167 Add changelog for v1.3
  CHANGELOG-1.3.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#170 Update images
  deploy/kubernetes/setup-csi-snapshotter.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS
