Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-12, with the labels that each got.

#429 Add certwatcher to webhook server
  go.mod
  pkg/validation-webhook/certwatcher.go
  pkg/validation-webhook/webhook.go
  pkg/validation-webhook/webhook_test.go
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.gitattributes
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XXL

#428 using csi driver from PV instead of from StorageClass
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#409 Add snapshot controller metrics
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#437 Prow update release 3.0
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#440 Cherry-pick:Add snapshot controller metrics
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XL

#435 Cherry-pick: Add certwatcher to webhook server
  go.mod
  pkg/validation-webhook/certwatcher.go
  pkg/validation-webhook/webhook.go
  pkg/validation-webhook/webhook_test.go
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.gitattributes
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, release-note, size/XXL

#441 Revert "Cherry-pick:Add snapshot controller metrics"
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#439 Bump csi-lib-utils to v0.9.0
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-validation-webhook/main.go
  go.mod
  go.sum
  pkg/validation-webhook/certwatcher.go
  pkg/validation-webhook/config.go
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/webhook.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XXL

#420 Switch to klog/v2
  cmd/snapshot-validation-webhook/main.go
  go.mod
  go.sum
  pkg/validation-webhook/config.go
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/webhook.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, release-note, size/M

#442 [Cherry-pick] Don't check for snapshotClass when deleting content
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#447 Increase resync-period default to 15 minutes
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#448 Update release-tools and prow script for release-2.1
  .prow.sh
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#446 Cherrypick #381 to 2.1.
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#449 Add change log for 2.1.3 release
  CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#425 Update controller based on snapshot v1 apis
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  deploy/kubernetes/webhook-example/admission-configuration-template
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_controller_test.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_update_test.go
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller_base.go
  pkg/sidecar-controller/snapshot_controller_test.go
  pkg/sidecar-controller/snapshot_delete_test.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/snapshot_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL

#452 Update snapshot-controller image to 3.0.3
  CHANGELOG/CHANGELOG-3.0.md
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#433 Don't change ReadyToUse in Snapshot when logging an event
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#453 Add changelog for release 4.0
  CHANGELOG/CHANGELOG-4.0.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#454 Update README for v4.0.0
  README.md
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
  examples/kubernetes/invalid-snapshot-v1.yaml
  examples/kubernetes/invalid-snapshot-v1beta1.yaml
  examples/kubernetes/snapshot-v1.yaml
  examples/kubernetes/snapshot-v1beta1.yaml
  examples/kubernetes/snapshotclass-v1.yaml
  examples/kubernetes/snapshotclass-v1beta1.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#458 master: update release-tools
  release-tools/build.make
  release-tools/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#457 Clarify instructions about validation webhook
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
