Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-05, with the labels that each got.

#296 Remove unwanted code conditions
  pkg/common-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#314 Move changelog files to a sub-folder
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-2.0.md
  CHANGELOG/CHANGELOG-2.1.md
  CHANGELOG/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#309 Update docs for controller namespace
  README.md
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#230 Fix the requeue logic
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller_base.go
  pkg/sidecar-controller/snapshot_delete_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#280 add metric to common controller - basic metrics utilities
  go.mod
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  v2/pkg/metrics/metrics.go
  v2/pkg/metrics/metrics_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XL
