Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-01, with the labels that each got.

#224 Stop calling CreateSnapshot when ReadyToUse is true
  pkg/sidecar-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#229 Fix typo in readme
  README.md
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#232 Remove PVC finalizer when no longer in use
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#233 Add changelog for release 2.0
  CHANGELOG-1.3.md
  CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#242 fix link
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#244 Add changelog for 2.0.1 release
  CHANGELOG-2.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS
