Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-10, with the labels that each got.

#387 Upgrade csi-lib-utils to 0.8.1
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#386 release-2.1: Update release tools for go build fix
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.sh
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
  release-tools/prow.sh
  release-tools/travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#348 Update Images
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#388 Upgrade csi-lib-utils to 0.8.1
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XL

#391 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#393 release-3.0: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#392 release-2.1: update release-tools
  go.mod
  go.sum
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#394 Add change log for 2.1.2 release
  CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#395 Create v3.0.1 change log
  CHANGELOG/CHANGELOG-3.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#397 update hyperlink for snaphshot validation webhook
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#396 Fix the failing multiarch builds
  cmd/csi-snapshotter/Dockerfile
  cmd/snapshot-controller/Dockerfile
  cmd/snapshot-validation-webhook/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#398 Cherry-pick #396: Fix the failing multiarch builds
  cmd/csi-snapshotter/Dockerfile
  cmd/snapshot-controller/Dockerfile
  cmd/snapshot-validation-webhook/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#375 Pass snapshot metadata to CSI driver
  cmd/csi-snapshotter/main.go
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller_base.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/M

#405 Revert to multiarch distroless base image
  cmd/csi-snapshotter/Dockerfile
  cmd/snapshot-controller/Dockerfile
  cmd/snapshot-validation-webhook/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#408 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#410 add instructions on creating volume snapshot quota for CRs
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/S

#413 Allow creation of snapshot content if pvc finalizer exists, even if pvc is marked for deletion.
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#414 Cherry pick #413 to release-3.0
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#415 Add changelog for 3.0.2
  CHANGELOG/CHANGELOG-3.0.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#416 Cherry-pick the fix for panic when source PVC does not exist
  CHANGELOG/CHANGELOG-3.0.md
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#417 Fix the changelog
  CHANGELOG/CHANGELOG-3.0.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
