Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-03, with the labels that each got.

#262 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#263 Fix error propagation in checkandAddSnapshotFinalizers and add tests
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_update_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#266 Add more sidecar tests and cleanup sidecar code
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#234 Update images
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#278 Include a nil check for the snapshotContent
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#275 Allows VolumeSnapshot to be deleted if the class isn't found
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, ok-to-test, release-note-none, size/S

#279 Moving nil check to correct location
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#265 doc: add workaround for hack/update-generated-code.sh
  hack/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/M

#282 Makes the number of worker threads configurable.
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/S
