Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-09, with the labels that each got.

#360 Fix the race between PVC finalizer and snapshot finalizer removal
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#367 Update volume snapshot CRDs to v1 version
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  client/hack/README.md
  client/hack/update-crd.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#376 Update client library dependency to k8s v1.19
  client/go.mod
  client/go.sum
  client/hack/README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#332 Add changelog for release 3.0
  CHANGELOG/CHANGELOG-3.0.md
  Makefile
  README.md
  cmd/snapshot-validation-webhook/Dockerfile
  cmd/snapshot-validation-webhook/main.go
  cmd/validation-webhook/Dockerfile
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#378 Fix image name for example webhook, and other nitpicks
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/README.md
  deploy/kubernetes/webhook-example/admission-configuration-template
  deploy/kubernetes/webhook-example/create-cert.sh
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#381 Fix panic when source PVC does not exist
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M
