Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-07, with the labels that each got.

#317 Fix requeue logic in the common controller
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_create_test.go
  vendor/k8s.io/kubernetes/pkg/util/goroutinemap/BUILD
  vendor/k8s.io/kubernetes/pkg/util/goroutinemap/OWNERS
  vendor/k8s.io/kubernetes/pkg/util/goroutinemap/exponentialbackoff/BUILD
  vendor/k8s.io/kubernetes/pkg/util/goroutinemap/exponentialbackoff/exponential_backoff.go
  vendor/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XL

#331 master: update release-tools
  release-tools/cloudbuild.yaml
  release-tools/filter-junit.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#284 Update Error in Snapshot Status
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_update_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#335 Call dynamic VS content creation unconditionally
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_update_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#334 chore: get rid of k8s.io/kubernetes dep
  go.mod
  go.sum
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
  pkg/utils/util_test.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/util/slice/BUILD
  vendor/k8s.io/kubernetes/pkg/util/slice/slice.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XL

#338 Adjusted the date printing to address unit test failure
  pkg/snapshotter/snapshotter.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#340 Move to klogv2
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  go.mod
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/metrics/metrics.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller_base.go
  pkg/snapshotter/snapshotter.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#344 Use separate client for leader election
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/S
