Repository kubernetes-csi/external-snapshotter, pull requests merged in 2020-04, with the labels that each got.

#283 Check if PVC is being used by a snapshot as source
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_update_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#281 Changelog for 2.1 release
  CHANGELOG-2.1.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#297 Add links to version in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#294 revamp find content logic to fix 290 291 292
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XXL

#301 Update prow
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#298 Re-enable k8s e2e tests in pull jobs
  .prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#302 Cherry pick of #298, #301: Re-enable k8s e2e tests
  .prow.sh
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#303 cherry-pick #293: revamp find content logic to fix 290 291 292
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
  pkg/utils/util.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XXL

#305 Nit: fix typos
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#304 Add changelog for 2.1.1 release
  CHANGELOG-2.1.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#289 Add event for snapshotting in progress
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_create_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS
