Repository kubernetes-csi/external-snapshotter, pull requests merged in 2021-07, with the labels that each got.

#537 update setup-csi-snapshotter.yaml csi-snapshotter image
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#542 release-4.1: update release-tools
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#541 master: update release-tools
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#540 Add "SnapshotCreated" event for snapshot-controller
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XS

#546 Update webhook README.md
  deploy/kubernetes/webhook-example/README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#550 Use distroless/static image for webhook
  cmd/snapshot-validation-webhook/Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#553 Fix some pathnames
  deploy/kubernetes/webhook-example/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#548 [release-3.0] Automated cherry pick of #470: Retain CreateSnapshot error
  pkg/sidecar-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#544 Remove redundant validation checks
  pkg/common-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#558 Update release tools 4.0
  OWNERS
  OWNERS_ALIASES
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/OWNERS
  release-tools/OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
  release-tools/pull-test.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#519 Add gauge metric for snapshot controller operations in flight
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L
