Repository kubernetes-csi/external-snapshotter, pull requests merged in 2021-08, with the labels that each got.

#536 snap client version update and kube dependency update
  go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#568 Change OWNERS_ALIASES to a symlink
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#547 [release-4.0] Automated cherry pick of #470: Retain CreateSnapshot error
  pkg/sidecar-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#570 Update k8s dependencies to v1.22.0
  README.md
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, sig/storage, size/L

#571 Fix recommended Kubernetes version in README
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, release-note-none, size/XS

#569 Add process_start_time_seconds metric
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/M

#574 Use csi-lib-utils v0.10.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/M, release-note

#575 Add options to configure leader election in snapshot-controller
  README.md
  cmd/snapshot-controller/main.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S

#573 Refactor http server and register leaderelection health check
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/sidecar-controller/snapshot_controller_base.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note

#576 Clean up .travis.yml
  .travis.yml
  README.md
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS, ok-to-test

#579 Add changelog for 4.2
  CHANGELOG/CHANGELOG-4.2.md
  README.md
  deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none

#581 Fix deadlock in recursive metric locks
  pkg/metrics/metrics.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, kind/flake, size/XS

#584 Add changelog for 4.2.1
  CHANGELOG/CHANGELOG-4.2.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#583 Fix deadlock in recursive metric locks
  pkg/metrics/metrics.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS

#586 Update images to v4.2.1
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/XS
