Repository kubernetes-csi/external-snapshotter, pull requests merged in 2021-04, with the labels that each got.

#496 Fix snapshotter metrics server to use http-endpoint when provided
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#497 Fix snapshotter metrics server to use httpEndpoint when provided
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XS

#503 Update to CSI spec 1.4
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#502 Correct snapshotContent error propagation
  pkg/sidecar-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#493 Change storage version from v1beta1 to v1
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note, size/S

#504 Make sure the v1 CRDs exist before starting the controller
  cmd/snapshot-controller/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/M

#505 Update reference implementation of the snapshot controller
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#507 Fix typo in CRD check
  cmd/snapshot-controller/main.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#509 Add changelog for 4.1.0
  CHANGELOG/CHANGELOG-4.1.md
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#510 Fix the compatibility table in README
  CHANGELOG/CHANGELOG-4.1.md
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS
