Repository kubernetes-csi/external-snapshotter, pull requests merged in 2021-06, with the labels that each got.

#529 correct snapshot controller installation doc
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#308 Add ability to customize VolumeSnapshotContent workqueue
  README.md
  cmd/csi-snapshotter/main.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller_base.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#530 Allow tuning common-controller Ratelimiter with `retryIntervalStart & retryIntervalMax`
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller_base.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#532 Use CSI spec v1.5.0
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note-none, size/XL

#527 Return VolumeSnapshotContent from various functions instead of nil
  pkg/common-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/L

#535 Add VS namespace to VSC printed columns
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XS

#538 Add command line arguments to configure leader election options
  README.md
  cmd/csi-snapshotter/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/S
