Repository kubernetes-csi/external-snapshotter, pull requests merged in 2021-12, with the labels that each got.

#623 Backport #606 to release-5.0
  README.md
  client/config/crd/kustomization.yaml
  deploy/kubernetes/csi-snapshotter/kustomization.yaml
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note, size/S, kind/design, ok-to-test

#621 Make the QPS and Burst of kube client config to be configurable
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  go.mod
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#625 Backport #621 to release-5.0
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  go.mod
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#626 Fixed the bug introduced by PR 621 and exposed the kube-api-qps cmd option properly
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  go.mod
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#628 Backport #626 to release-5.0
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  go.mod
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#616 Rename KUBE_NODE_NAME to NODE_NAME
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/XS

#633 Rename KUBE_NODE_NAME to NODE_NAME
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS

#585 Implement distributed snapshotting
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  go.mod
  go.sum
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_controller_test.go
  pkg/utils/util.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XL, release-note

#634 Backport #585 to release 5.0
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  go.mod
  go.sum
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_controller_test.go
  pkg/utils/util.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XL, release-note

#635 Add changelog for v5.0.0
  CHANGELOG/CHANGELOG-5.0.md
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none

#636 Backport changelog to release-5.0
  CHANGELOG/CHANGELOG-5.0.md
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none
