Repository kubernetes-csi/external-snapshotter, pull requests merged in 2022-11, with the labels that each got.

#777 Parameterize startup CRD wait retries
  README.md
  cmd/snapshot-controller/main.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S

#775 update sidecars to latest version
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS

#781 release-4.2: update release-tools
  client/apis/volumesnapshot/v1/types.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/register.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/prow.sh
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/scheme/register.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#782 release-5.0: update release-tools
  client/apis/volumesnapshot/v1/types.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/register.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/prow.sh
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/clientset/versioned/scheme/register.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#783 release-6.0: update release-tools
  client/apis/volumesnapshot/v1/types.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/register.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/prow.sh
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/scheme/register.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#785 Fix client-go version
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XL, release-note-none

#786 release-6.1: update release-tools
  go.mod
  go.sum
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/prow.sh
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#787 add dependabot configuration to github actions for auto update PRs
  .github/workflows/dependabot.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#788 remove `replace` directive from the go.mod file
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none
