Repository kubernetes-csi/external-snapshotter, pull requests merged in 2022-12, with the labels that each got.

#793 Make webhook example compatible with TLS secrets
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS, ok-to-test

#795 test: fix trivy and codespell github action failure
  .github/workflows/codespell.yml
  .github/workflows/trivy.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, kind/failing-test, size/XS

#796 fix certificate generation in webhook example
  deploy/kubernetes/webhook-example/create-cert.sh
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS, ok-to-test

#797 Update dependency go modules for k8s v1.26.0
  client/go.mod
  client/go.sum
  client/vendor/golang.org/x/net/http2/headermap.go
  client/vendor/golang.org/x/net/http2/hpack/encode.go
  client/vendor/golang.org/x/net/http2/server.go
  client/vendor/golang.org/x/net/http2/transport.go
  client/vendor/golang.org/x/sys/execabs/execabs_go119.go
  client/vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  client/vendor/golang.org/x/sys/unix/syscall_linux.go
  client/vendor/golang.org/x/sys/windows/syscall_windows.go
  client/vendor/golang.org/x/sys/windows/zsyscall_windows.go
  client/vendor/golang.org/x/term/terminal.go
  client/vendor/golang.org/x/text/unicode/bidi/trieval.go
  client/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/sockcmsg_unix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/XL, release-note-none

#798 Update client dep to golang.org/x/net v0.4.0
  client/go.mod
  client/go.sum
  client/vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note-none

#801 Add replace clause back to go.mod
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#802 Upgrade csi-lib-utils to v0.12.0
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/metrics/metrics.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#800 Add changelog for v6.2.0
  CHANGELOG/CHANGELOG-6.2.md
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none
