Repository kubernetes-csi/external-snapshotter, pull requests merged in 2022-03, with the labels that each got.

#666 Allow resync on VolumeSnapshotContent when there is no error from CreateSnapshot
  pkg/sidecar-controller/snapshot_controller_base.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#668 Cherrypick #653 to release-5.0 branch
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS, ok-to-test

#665 Update generated code for SourceVolumeMode field in VolumeSnapshotContents
  client/apis/volumesnapshot/v1/types.go
  client/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  client/apis/volumesnapshot/v1beta1/zz_generated.deepcopy.go
  client/clientset/versioned/clientset.go
  client/clientset/versioned/doc.go
  client/clientset/versioned/fake/clientset_generated.go
  client/clientset/versioned/fake/doc.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/doc.go
  client/clientset/versioned/scheme/register.go
  client/clientset/versioned/typed/volumesnapshot/v1/doc.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/doc.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot_client.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotclass.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotcontent.go
  client/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  client/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  client/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  client/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  client/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/doc.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/doc.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshot_client.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotclass.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/fake/fake_volumesnapshotcontent.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/generated_expansion.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshot_client.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotclass.go
  client/clientset/versioned/typed/volumesnapshot/v1beta1/volumesnapshotcontent.go
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  client/go.mod
  client/go.sum
  client/hack/README.md
  client/hack/update-crd.sh
  client/informers/externalversions/factory.go
  client/informers/externalversions/generic.go
  client/informers/externalversions/internalinterfaces/factory_interfaces.go
  client/informers/externalversions/volumesnapshot/interface.go
  client/informers/externalversions/volumesnapshot/v1/interface.go
  client/informers/externalversions/volumesnapshot/v1/volumesnapshot.go
  client/informers/externalversions/volumesnapshot/v1/volumesnapshotclass.go
  client/informers/externalversions/volumesnapshot/v1/volumesnapshotcontent.go
  client/informers/externalversions/volumesnapshot/v1beta1/interface.go
  client/informers/externalversions/volumesnapshot/v1beta1/volumesnapshot.go
  client/informers/externalversions/volumesnapshot/v1beta1/volumesnapshotclass.go
  client/informers/externalversions/volumesnapshot/v1beta1/volumesnapshotcontent.go
  client/listers/volumesnapshot/v1/expansion_generated.go
  client/listers/volumesnapshot/v1/volumesnapshot.go
  client/listers/volumesnapshot/v1/volumesnapshotclass.go
  client/listers/volumesnapshot/v1/volumesnapshotcontent.go
  client/listers/volumesnapshot/v1beta1/expansion_generated.go
  client/listers/volumesnapshot/v1beta1/volumesnapshot.go
  client/listers/volumesnapshot/v1beta1/volumesnapshotclass.go
  client/listers/volumesnapshot/v1beta1/volumesnapshotcontent.go
Labels: lgtm, approved, cncf-cla: yes, size/XXL, release-note, kind/api-change

#672 Backport: Avoid constantly retries CreateSnapshot call on error without exponential backoff
  pkg/sidecar-controller/snapshot_controller_base.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test
