Repository kubernetes-csi/external-snapshotter, pull requests merged in 2022-05, with the labels that each got.

#708 test: add tirvy vulnerability scanner github action
  .github/workflows/trivy.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note-none, kind/failing-test

#706 Adding webhook RBAC to enable validation of snapshotclasses
  deploy/kubernetes/webhook-example/README.md
  deploy/kubernetes/webhook-example/rbac-snapshot-webhook.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/M, release-note, ok-to-test

#710 Backport-706 Adding webhook RBAC to enable validation of snapshotclasses
  deploy/kubernetes/webhook-example/README.md
  deploy/kubernetes/webhook-example/rbac-snapshot-webhook.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/M, release-note, ok-to-test

#713 README changes to release-6.0 branch
  README.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/XS

#714 Backport 690: replace serviceAccountName key, rbac and cleanup in the code
  cmd/snapshot-controller/main.go
  deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_test.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_finalizer_test.go
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
  pkg/utils/util.go
  pkg/validation-webhook/scheme.go
  pkg/validation-webhook/webhook.go
  pkg/validation-webhook/webhook_test.go
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#715 Remove v1beta1 examples
  deploy/kubernetes/webhook-example/README.md
  examples/kubernetes/invalid-snapshot-v1beta1.yaml
  examples/kubernetes/snapshot-v1beta1.yaml
  examples/kubernetes/snapshotclass-v1beta1.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note-none

#711 Add changelog for v6.0
  CHANGELOG/CHANGELOG-6.0.md
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/documentation, release-note-none

#716 Backport 715: Remove v1beta1 examples
  deploy/kubernetes/webhook-example/README.md
  examples/kubernetes/invalid-snapshot-v1beta1.yaml
  examples/kubernetes/snapshot-v1beta1.yaml
  examples/kubernetes/snapshotclass-v1beta1.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note-none

#717 Backport 711: Add changelog for v6.0
  CHANGELOG/CHANGELOG-6.0.md
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/documentation, release-note-none

#718 Add back v1beta1 manifests
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  client/hack/README.md
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, kind/api-change

#719 Backport 718: Add back v1beta1 manifests
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  client/hack/README.md
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, kind/api-change

#721 Backport 720: Update changelog 6.0.1
  CHANGELOG/CHANGELOG-6.0.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/XS
