Repository kubernetes-csi/external-snapshotter, pull requests merged in 2022-01, with the labels that each got.

#641 release-5.0: Update release tools 5.0
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#640 Update release tools 5.0
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#642 Change snapshot controller image version to 4.2.1
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#643 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note-none

#647 doc: add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/support.md
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/documentation, release-note-none

#645 remove storage class permissions from snapshot controller cluster role
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/XS, ok-to-test

#653 Change snapshot controller image version to 5.0.1
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test
