Repository kubernetes-csi/external-snapshotter, pull requests merged in 2022-09, with the labels that each got.

#756 use registry.k8s.io for deployment
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note-none, size/S, ok-to-test

#759 Fix CVE-2022-27664 by updating golang.org/x/net pacckage
  go.mod
  go.sum
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#758 make the formatting errors based on go 1.19
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#760 update client package with go 1.19 formatting changes
  client/apis/volumesnapshot/v1/types.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/register.go
  pkg/common-controller/snapshot_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note-none

#762 declare go1.18 in the go.mod
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/scheme/register.go
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#761 Upgrade go version and code-generator in snapshotter client
  client/clientset/versioned/clientset.go
  client/go.mod
  client/go.sum
  client/hack/README.md
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note

#767 Add changelog for v6.1.0
  CHANGELOG/CHANGELOG-6.1.md
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none

#768 Update client to v6.1.0
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/XS

#766 Update deployment tags to v6.1.0
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/XS
