Repository kubernetes-csi/external-snapshotter, pull requests merged in 2022-04, with the labels that each got.

#682 master: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS

#683 Change SourceVolumeMode type to v1.PersistentVolumeMode
  client/apis/volumesnapshot/v1/types.go
  client/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/zz_generated.deepcopy.go
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note, kind/api-change

#684 Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#674 Add default validation for VolumeSnapshotClass
  pkg/validation-webhook/scheme.go
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/snapshot_test.go
  pkg/validation-webhook/webhook.go
  pkg/validation-webhook/webhook_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#686 [Cherry-pick] Change SourceVolumeMode type to v1.PersistentVolumeMode.
  client/apis/volumesnapshot/v1/types.go
  client/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/zz_generated.deepcopy.go
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note, kind/api-change

#685 Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#679 Changes to snapshot controller to add sourceVolumeMode
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S

#692 release-6.0: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS

#691 release-5.0: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS

#694 [Cherry-pick] Changes to snapshot controller to add SourceVolumeMode to VolumeSnapshotContents
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S

#693 Backport 674: Adding validation for default snapshot classes per driver
  pkg/validation-webhook/scheme.go
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/snapshot_test.go
  pkg/validation-webhook/webhook.go
  pkg/validation-webhook/webhook_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#689 Remove create and delete from csi-snapshotter RBAC
  deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/XS, ok-to-test

#688 Updating readme and webhook tempate to capture changes made for volumesnapshotclasses
  README.md
  deploy/kubernetes/webhook-example/admission-configuration-template
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S, ok-to-test

#696 Backport: Remove create and delete from csi-snapshotter RBAC
  deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS, ok-to-test

#697 Update comment in types.go for the new CRD docs
  client/apis/volumesnapshot/v1/types.go
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS, ok-to-test

#698 Backport: Update comment in types.go, to be included in the new CRD docs
  client/apis/volumesnapshot/v1/types.go
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS, ok-to-test

#680 Add webhook to make SourceVolumeMode immutable
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/webhook.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S

#701 Backport: Add webhook to make SourceVolumeMode immutable
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/webhook.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S

#702 Update README with prevent-volume-mode-conversion feature flag
  README.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/XS

#690 replace serviceAccountName key, rbac and cleanup in the code
  cmd/snapshot-controller/main.go
  deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_test.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_finalizer_test.go
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
  pkg/utils/util.go
  pkg/validation-webhook/scheme.go
  pkg/validation-webhook/webhook.go
  pkg/validation-webhook/webhook_test.go
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#700 Backport 688: Updating readme and webhook tempate to capture changes made for volumesnapshotclasses
  README.md
  deploy/kubernetes/webhook-example/admission-configuration-template
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, size/S, release-note-action-required, ok-to-test
