Repository kubernetes-csi/external-snapshotter, pull requests merged in 2023-09, with the labels that each got.

#864 check if the csi driver is supported the volume group snapshot cap
  cmd/csi-snapshotter/main.go
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/rpc/common.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note

#900 release tools update
  release-tools/SIDECAR_RELEASE_PROCESS.md
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#901 Disable VolumeGroupSnapshot feature flag
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S

#902 Update K8s deps to 0.28.0 and update generated code in the client
  client/clientset/versioned/doc.go
  client/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/fake/fake_volumegroupsnapshot.go
  client/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/fake/fake_volumegroupsnapshotclass.go
  client/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/fake/fake_volumegroupsnapshotcontent.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotclass.go
  client/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotcontent.go
  client/go.mod
  client/hack/README.md
  client/informers/externalversions/factory.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/fake/fake_volumegroupsnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/fake/fake_volumegroupsnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumegroupsnapshot/v1alpha1/fake/fake_volumegroupsnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/informers/externalversions/factory.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note

#904 Update client lib version to 6.3.0
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#907 Remove direct dependency on k8s.io/kubernetes
  go.mod
  go.sum
  pkg/validation-webhook/convert_test.go
  pkg/validation-webhook/fuzzer.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#908 Add changelog for v6.3.0
  CHANGELOG/CHANGELOG-6.3.md
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none

#876 Update VolumeSnapshot and VolumeSnapshotContent using JSON patch
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_finalizer_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#844 chore: Adopt kubernetes recommand label
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/S, ok-to-test
