Repository kubernetes-csi/external-snapshotter, pull requests merged in 2023-12, with the labels that each got.

#974 Update VolumeSnapshot and VolumeSnapshotContent using JSON patch
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_finalizer_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#977 Update release tools to fix broken image build pipeline
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-modules-update.sh
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#916 Enable prevent-volume-mode-conversion by default following k8s 1.28 release
  README.md
  cmd/snapshot-controller/main.go
  pkg/validation-webhook/webhook.go
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-action-required, size/XS, ok-to-test

#982 Update csi-lib-utils to v0.17.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#983 Update go modules
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#985 Changelog for v6.3.3
  CHANGELOG/CHANGELOG-6.3.md
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S
