Repository kubernetes-csi/external-snapshotter, pull requests merged in 2023-10, with the labels that each got.

#918 bump up gopkg.in/yaml.v3 to address CVE-2022-28948
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/M, release-note-none

#914 Change snapshot controller image version to 6.2.2 in release-6.2 branch
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#926 Update tools
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS

#934 Add changelog for v6.0.1
  CHANGELOG/CHANGELOG-6.0.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#932 Add changelog for v6.2.3
  CHANGELOG/CHANGELOG-6.2.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#922 add cmdline args to enable group snapshot webhooks
  deploy/kubernetes/webhook-example/webhook.yaml
  pkg/validation-webhook/webhook.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/M, release-note, ok-to-test

#941 Add Changelog for v6.3.1
  CHANGELOG/CHANGELOG-6.3.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#944 Snapshot controller deployment update
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS

#942 Change snapshot controller image version to 6.2.3 in release-6.2 branch
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#943 Change snapshot controller image version to 6.3.1 in release-6.3 branch
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#846 Fix CRDs missing metadata fields
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  client/hack/README.md
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/M, release-note-none, ok-to-test
