Repository kubernetes-csi/external-snapshotter, pull requests merged in 2023-11, with the labels that each got.

#882 DeleteVolumeGroupSnapshot API - part 1
  cmd/snapshot-controller/main.go
  deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/group_snapshotter/group_snapshotter.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/patch.go
  pkg/utils/util.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XL, release-note

#954 Bump google.golang.org/grpc to fix CVE-2023-44487
  go.mod
  go.sum
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/XL, release-note, ok-to-test

#956 Add changelog for v6.3.2
  CHANGELOG/CHANGELOG-6.3.md
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/documentation, release-note-none, ok-to-test

#959 Allow csi-snapshotter to create and manage VolumeSnapshots
  deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#961 Allow snapshot controller to delete VolumeSnapshots
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#958 Requeue un-ready volume snapshots
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_controller_base.go
  pkg/sidecar-controller/snapshot_delete_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note

#952 DeleteVolumeGroupSnapshot API - part 2
  client/hack/update-crd.sh
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/snapshot_controller.go
  pkg/sidecar-controller/content_create_test.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/sidecar-controller/snapshot_delete_test.go
  pkg/snapshotter/snapshotter.go
  pkg/snapshotter/snapshotter_test.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/L, release-note

#966 Add VolumeGroupSnaphot examples
  examples/kubernetes/groupsnapshot-v1alpha1.yaml
  examples/kubernetes/groupsnapshotclass-v1alpha1.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S, ok-to-test
