Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-08, with the labels that each got.

#1124 Update controller deployment to latest version
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#1137 cleanup: Update csi release tools
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, release-note, size/S

#1132 Cherrypick #1124 Update controller deployment to latest version
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#1139 Bump Kubernetes to v1.31.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note, ok-to-test

#1120 Document Volume Group Snapshot feature in the README file
  README.md
  client/config/crd/kustomization.yaml
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/documentation, release-note

#1145 Fix scheduleOpsInFlightMetric go routine leak
  pkg/metrics/metrics.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note-none, size/S, ok-to-test

#1115 Look for a VolumeGroupSnapshotClass when getting the class of a VolumeGroupSnapshot
  pkg/common-controller/groupsnapshot_controller_helper.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/XS

#1118 Add group snapshot controller unit tests
  pkg/common-controller/framework_test.go
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/groupsnapshot_create_test.go
  pkg/common-controller/groupsnapshot_delete_test.go
  pkg/common-controller/groupsnapshot_finalizer_test.go
  pkg/common-controller/groupsnapshot_update_test.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_finalizer_test.go
  pkg/common-controller/snapshot_update_test.go
Labels: lgtm, approved, cncf-cla: yes, size/XXL, kind/cleanup, release-note-none

#1133 [snapshot-controller] Retry PVC finalizer removal on conflict
  pkg/common-controller/snapshot_controller.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#1147 Remove unwanted file
  CHANGELOG/release-notes-1496540165
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#1146 Remove unwanted file
  CHANGELOG/release-notes-1496540165
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#1143 Create changelog v8.1.0
  CHANGELOG/CHANGELOG-8.1.md
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none, ok-to-test
