Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-11, with the labels that each got.

#1174 Update CSI Spec
  cmd/csi-snapshotter/main_test.go
  go.mod
  go.sum
  pkg/snapshotter/snapshotter_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/driver-controller.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/driver.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/driver.mock.go
  vendor/github.com/kubernetes-csi/csi-test/v5/driver/mock.go
  vendor/github.com/kubernetes-csi/csi-test/v5/utils/protobuf_matcher.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/XXL, release-note, ok-to-test

#1171 Centralize VolumeGroupSnapshot members resource creation in the snapshot-controller
  deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note

#1184 Remove volumeGroupSnapshotRef immutable validation rule
  client/apis/volumegroupsnapshot/v1alpha1/types.go
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/types.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS

#1187 test: fix trivy action
  .github/workflows/trivy.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, kind/failing-test, size/XS

#1177 Set PVC name on VolumeGroupSnapshot members
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/snapshot_controller.go
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note

#1173 Add secrets for Get VolumeGroupSnapshot
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#1193 Pass context on in GroupSnapshot sync functions
  pkg/common-controller/framework_test.go
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/snapshot_controller_base.go
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#1198 Set VolumeHandle for dynamically provisioned VolumeGroupSnapshots
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note

#1194 include feature gate in snapshotter
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  go.mod
  go.sum
  pkg/features/features.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/dbstats_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_go116.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/process_collector.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go
  vendor/k8s.io/component-base/cli/flag/colon_separated_multimap_string_string.go
  vendor/k8s.io/component-base/cli/flag/configuration_map.go
  vendor/k8s.io/component-base/cli/flag/flags.go
  vendor/k8s.io/component-base/cli/flag/langle_separated_map_string_string.go
  vendor/k8s.io/component-base/cli/flag/map_string_bool.go
  vendor/k8s.io/component-base/cli/flag/map_string_string.go
  vendor/k8s.io/component-base/cli/flag/namedcertkey_flag.go
  vendor/k8s.io/component-base/cli/flag/noop.go
  vendor/k8s.io/component-base/cli/flag/omitempty.go
  vendor/k8s.io/component-base/cli/flag/sectioned.go
  vendor/k8s.io/component-base/cli/flag/string_flag.go
  vendor/k8s.io/component-base/cli/flag/string_slice_flag.go
  vendor/k8s.io/component-base/cli/flag/tristate.go
  vendor/k8s.io/component-base/featuregate/OWNERS
  vendor/k8s.io/component-base/featuregate/feature_gate.go
  vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
  vendor/k8s.io/component-base/metrics/prometheus/feature/metrics.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/XXL, release-note, ok-to-test

#1200 Remove PVCVolumeSnapshotRefList from VolumeGroupSnapshot API
  client/apis/volumegroupsnapshot/v1alpha1/types.go
  client/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/utils/util.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note, kind/api-change

#1204 Only dynamic provisioning for an independent snapshot needs a snapshot class
  pkg/sidecar-controller/snapshot_controller.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S

#1209 update CSI spec to have official version
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS, ok-to-test

#1210 Do not panic when a default snapshotclass does not exist
  pkg/sidecar-controller/snapshot_controller.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note-none, size/S

#1216 Prevent infinite loop deleting group snapshots
  pkg/common-controller/groupsnapshot_controller_helper.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/XS

#1219 use annotation to store the groupsnapshot handle
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/S

#1217 Add error checking to processGroupSnapshotWithDeletionTimestamp
  pkg/common-controller/groupsnapshot_controller_helper.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note-none, size/XS

#1222 remove unused labels from util
  pkg/common-controller/framework_test.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#1224 Add the group snapshot bound finalizer when deletionPolicy is set to Retain
  pkg/common-controller/groupsnapshot_controller_helper.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/XS

#1163 ci: use go version from go.mod for trivy
  .github/workflows/trivy.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS
