Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-03, with the labels that each got.

#1037 Changelog for v6.3.4
  CHANGELOG/CHANGELOG-6.3.md
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#1040 Changelog for v7.0.2
  CHANGELOG/CHANGELOG-7.0.md
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#1034 Add snapshot secret reference to group snapshot controller.
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#1044 [release-7.0]: Fix logging in the volumegroupsnapshot methods
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/S, ok-to-test

#1046 [release-7.0] Add snapshot size to VSC created for VGS
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/sidecar-controller/snapshot_controller.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#1047 [release-7.0] Add snapshot secret reference to group snapshot controller.
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/util.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#1031 Update controller deployment to latest version
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, kind/design, size/XS, ok-to-test
