Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-12, with the labels that each got.

#1225 Use ownership to identify volume group snapshot members
  go.mod
  pkg/common-controller/framework_test.go
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/util.go
  pkg/utils/vgs.go
  pkg/utils/vgs_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note

#1229 replace deprecated Queue and RateLimiter
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/sidecar-controller/framework_test.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/sidecar-controller/snapshot_controller_base.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note-none

#1228 replace enable-volume-group-snapshots with featuregate
  README.md
  cmd/csi-snapshotter/main.go
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S

#1235 Change CreationTime in VolumeGroupSnapshotContentStatus from *int64 to *metav1.Time
  client/apis/volumegroupsnapshot/v1beta1/types.go
  client/apis/volumegroupsnapshot/v1beta1/zz_generated.deepcopy.go
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  pkg/common-controller/framework_test.go
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumegroupsnapshot/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/S, kind/api-change

#1237 Update the API Approved Annotation for volume group snapshots
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/XS

#1238 Fix Snapshot Controller's unbounded VolumeSnapshot list call on startup
  cmd/snapshot-controller/main.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS

#1239 Add release notes for v8.2.0
  CHANGELOG/CHANGELOG-8.2.md
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none

#1152 Add nil check for groupSnapshotContent in deleteCSIGroupSnapshotOperaion and unit tests
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/sidecar-controller/groupsnapshot_helper_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note-none, ok-to-test

#1243 Add changelog for 8.0.2
  CHANGELOG/CHANGELOG-8.0.md
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/documentation, release-note-none

#1244 [release-8.1] Bump to go v1.23.1 to fix trivy
  .github/workflows/trivy.yaml
  go.mod
  go.sum
  release-tools/build.make
  release-tools/prow.sh
  release-tools/pull-test.sh
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/modules.txt
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/cleanup, release-note-none

#1250 Update release tools
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note-none, ok-to-test

#1252 [release-8.1] Fix image-push by updating release-tools
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#1247 Add changelog for 8.1.1
  CHANGELOG/CHANGELOG-8.1.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#1246 Update deployment with v8.0.2
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#1245 Update deployment to v8.2.0
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#1253 Update deployment with v8.1.1
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS
