Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-02, with the labels that each got.

#1005 Add nil check for SourceVolumeMode in the validation webhook
  pkg/validation-webhook/snapshot.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/XS

#1006 Add nil check for SourceVolumeMode in the ValidationWebHook
  pkg/validation-webhook/snapshot.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/XS

#1008 Add changelog 7.0.1
  CHANGELOG/CHANGELOG-7.0.md
Labels: lgtm, approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#1011 Add snapshot size to VSC created for VGS
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/sidecar-controller/snapshot_controller.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#1014 Fix logging in the volumegroupsnapshot methods
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S, ok-to-test

#1015 Fix detecting default annotation on VolumeGroupSnapshotClass
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/snapshot_controller.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note

#1020 Update release tools with go version fix
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#1009 Discard unnecessary VolumeSnapshotContent updates to prevent rapid RPC calls
  pkg/sidecar-controller/snapshot_controller_base.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note
