Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-04, with the labels that each got.

#1051 use group secret for GetGroupSnapshotStatus
  pkg/group_snapshotter/group_snapshotter.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/groupsnapshot_helper.go
Labels: lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#1058 Sync dependabot config from external-provisioner
  .github/dependabot.yaml
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#1049 replace custom ContainsString() with standard slices.Contains()
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/sidecar-controller/snapshot_controller.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note-none

#1066 Avoid conflicts in updateSnapshotContentStatus
  pkg/sidecar-controller/snapshot_controller.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#1067 Avoid panicking when snapshotting a non-CSI PV
  pkg/common-controller/groupsnapshot_controller_helper.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test
