Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-05, with the labels that each got.

#1073 Adding validation rules into CRDs for validation
  client/apis/volumegroupsnapshot/v1alpha1/types.go
  client/apis/volumesnapshot/v1/types.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#1084 Update vendor
  .github/workflows/trivy.yaml
  go.mod
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumesnapshot/v1/types.go
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note-none

#1085 Ensure vendor checks are run for all modules
  Makefile
  client/go.mod
  hack/verify-vendor.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note-none

#1075 Update code-generator to 1.30.0
  client/hack/README.md
  client/hack/update-generated-code.sh
Labels: lgtm, approved, cncf-cla: yes, size/M, kind/cleanup, release-note

#1076 Update manifests based on new CRD validation rules
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotclasses.yaml
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  client/hack/README.md
  client/hack/update-crd.sh
Labels: lgtm, approved, cncf-cla: yes, size/XXL, release-note

#1063 Update controller deployment to latest version
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
  deploy/kubernetes/webhook-example/webhook.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/XS, ok-to-test

#1068 API change to improve VolumeGroupSnapshot restore
  client/apis/volumegroupsnapshot/v1alpha1/types.go
  client/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/util.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v7/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, kind/api-change, ok-to-test

#1089 Fix typo
  client/hack/README.md
  client/hack/run-cel-tests.sh
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S, ok-to-test

#1069 Link PVCs and PVs in VolumeGroupSnapshot and VolumeGroupSnapshotContent
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/utils/pvs.go
  pkg/utils/pvs_test.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#1091 Remove duplicate validation logic from webhook
  deploy/kubernetes/webhook-example/admission-configuration-template
  pkg/common-controller/snapshot_controller.go
  pkg/validation-webhook/groupsnapshot.go
  pkg/validation-webhook/groupsnapshot_test.go
  pkg/validation-webhook/snapshot.go
  pkg/validation-webhook/snapshot_test.go
  pkg/validation-webhook/validation.go
  pkg/validation-webhook/webhook.go
Labels: lgtm, approved, cncf-cla: yes, size/XXL, kind/cleanup, release-note

#1094 Use a marker for the Namespace VSC additional printer column
  client/apis/volumesnapshot/v1/types.go
  client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  client/hack/README.md
  pkg/utils/patch.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v8/apis/volumesnapshot/v1/types.go
Labels: lgtm, approved, cncf-cla: yes, kind/cleanup, release-note, size/XS

#1095 Add changelog for v8.0
  CHANGELOG/CHANGELOG-8.0.md
  CHANGELOG/release-notes-1496540165
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none
