Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-01, with the labels that each got.

#987 Fix the max duration to wait for CRDs in the snapshot-controller
  README.md
  cmd/snapshot-controller/main.go
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/M, release-note, ok-to-test

#971 Update API for pre provisioned group snapshots
  client/apis/volumegroupsnapshot/v1alpha1/types.go
  client/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  client/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshotcontents.yaml
  client/hack/README.md
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/groupsnapshot_helper.go
  pkg/sidecar-controller/snapshot_controller_base.go
  pkg/validation-webhook/groupsnapshot.go
  pkg/validation-webhook/groupsnapshot_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/zz_generated.deepcopy.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, kind/api-change

#995 Selector in VolumeGroupSnapshotSource API should be optional
  client/apis/volumegroupsnapshot/v1alpha1/types.go
  client/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
  client/config/crd/groupsnapshot.storage.k8s.io_volumegroupsnapshots.yaml
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/validation-webhook/groupsnapshot_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumegroupsnapshot/v1alpha1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumegroupsnapshot/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, cncf-cla: yes, size/M, release-note, kind/api-change

#837 implement GroupSnapshotter.GetGroupSnapshotStatus()
  pkg/group_snapshotter/group_snapshotter.go
  pkg/sidecar-controller/csi_handler.go
  pkg/sidecar-controller/groupsnapshot_helper.go
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/M, release-note

#999 Add changelog 7.0
  CHANGELOG/CHANGELOG-7.0.md
Labels: lgtm, approved, cncf-cla: yes, size/L, kind/documentation, release-note-none
