Repository kubernetes-csi/external-snapshotter, pull requests merged in 2024-06, with the labels that each got.

#1104 Changelog for v8.0.1
  CHANGELOG/CHANGELOG-8.0.md
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S, ok-to-test

#1107 Add group snapshot controller metrics
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_group.go
  pkg/metrics/metrics_test.go
Labels: lgtm, approved, cncf-cla: yes, size/L, release-note, ok-to-test

#1098 Avoid group snapshot provisioning with mismatching CSI Drivers
  pkg/common-controller/groupsnapshot_controller_helper.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, release-note, size/S

#1100 Correctly detect newly created Volume[Group]SnapshotClasses
  pkg/common-controller/groupsnapshot_controller_helper.go
  pkg/common-controller/snapshot_controller.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/M, release-note
