Repository kubernetes-csi/external-snapshotter, pull requests merged in 2025-05, with the labels that each got.

#1292 fix: CVE-2025-22872
  .github/workflows/trivy.yaml
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: kind/bug, lgtm, approved, cncf-cla: yes, size/L, release-note

#1290 Update controller deployment to latest version
  deploy/kubernetes/csi-snapshotter/setup-csi-snapshotter.yaml
  deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
Labels: lgtm, approved, cncf-cla: yes, release-note, size/XS, ok-to-test

#1294 fix: use voluegroupsnapshot uid to make snapshotname
  pkg/common-controller/groupsnapshot_controller_helper.go
Labels: kind/bug, kind/feature, lgtm, approved, cncf-cla: yes, release-note, size/S, ok-to-test

#1296 Upgrade release tools
  release-tools/prow.sh
Labels: lgtm, approved, cncf-cla: yes, release-note-none, size/S, ok-to-test

#1304 Add `-automaxprocs` flag for configuring `GOMAXPROCS`
  README.md
  cmd/csi-snapshotter/main.go
  cmd/snapshot-controller/main.go
  go.mod
  go.sum
  vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go
  vendor/github.com/kubernetes-csi/csi-lib-utils/standardflags/automaxprocs.go
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: kind/feature, lgtm, approved, cncf-cla: yes, size/XXL, release-note
